ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "roles" TEXT;

UPDATE "User"
SET "roles" = CAST("role" AS TEXT)
WHERE "roles" IS NULL;

ALTER TABLE "User" ALTER COLUMN "roles" SET DEFAULT '1';
ALTER TABLE "User" ALTER COLUMN "roles" SET NOT NULL;
